# Generated by Django 3.1.1 on 2021-09-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_add', models.DateTimeField(auto_now=True)),
                ('time_done', models.DateTimeField()),
                ('outcome', models.BooleanField(blank=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Planowane'), (2, 'Wykonane')])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ilość')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Produkt')),
            ],
        ),
    ]
