# Generated by Django 3.1.1 on 2021-09-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.BooleanField(blank=True),
        ),
    ]
