# Generated by Django 3.1.1 on 2021-05-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('service_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.sgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_barcode', models.CharField(max_length=50, unique=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Ptype', models.CharField(choices=[('1', 'Farba'), ('2', 'Pielęgnacja'), ('3', 'Sprzedaż')], max_length=1)),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.pgroup')),
            ],
        ),
    ]
